### ISSUE TITLE
Add Version Tags

### ISSUE THREAD

**Issue by K-Leon** [couchbase/couchbase-lite-java-ce-root#10]
Is it possible to add the Version Tags to this repo too? (2.7.x especially)

Thanks for your hard work!

**Comment by bmeike** [comment]
Yes.  Sorry about that.  I've been trying to keep up, but have not been completely successful.

FWIW, I very much doubt that it is possible to build 2.7 from this repository and I doubt that that will ever change.  It isn't that it couldn't be done, it is just that it is a tremendous amount of work.

If you need to build 2.7 you will probably need to do it from the deprecated repo structure.

(and, fwiw, my apologies for *that* as well.  2 complete restructurings in under 2 years is a PITA.  It was necessitated by our build/release process)

**Comment by K-Leon** [comment]
My problem is that there is right now no way to determine the proper commits of the submodules which went into the release. So I have no Chance to build anything else that isn‘t current master.

I don‘t change a lot besides the retry logic if the device is offline. That‘s the sole reason that is left on my side. I need way more aggressive polling to overcome hardware bugs on a few devices. But this means a recompile of every Version and due to production readiness I can‘t use master for this.

Do you have any idea how to handle this?

**Comment by bmeike** [comment]
Yes.
 
The repository couchbase/couchbase-lite-android-ce is mostly what you need.  You might want to check that each one of the top-level submodules is checked out on the "release/mercury" branch (for the java repo, "release/android/mercury")

**Comment by bmeike** [comment]
@K-Leon 
I have just updated the old repository, (couchbase/couchbase-lite-android-ce) so that the master branch should correctly build CBL Java/Android 2.7.1, the latest build supported by that repo..  Please re-open this issue if you have any troubles with it.
