### ISSUE TITLE
Milestone for first release

### ISSUE THREAD

**Issue by currious** [couchbase/couchbase-lite-java-ce-root#11]
Hello,

are there still any milestones planed for your first release?
At the moment we are using this repo https://github.com/couchbase/couchbase-lite-java that you marked as deprecated.
Will be there much effort of migrating our code to this new repository?
We don't have any extra coding. We just make use of the com.couchbase.lite.Database class

Thx.

**Comment by bmeike** [comment]
That repo is, as noted, deprecated.  It is not supported.  You should transition from it as soon as possible.

Couchbase Lite v2.8 was released on Oct 15.
