### ISSUE TITLE
start multiple replicator can crash on android device 

### ISSUE THREAD

**Issue by xiaomingz** [couchbase/couchbase-lite-java-ce-root#14]
when we start multiple replicator at the same time, it mush crash after run 2-3 minute，we use android sdk version is 2.8.1 and client/gateway/server is community version, here is our demoActivity and crash logs.

[MultipleCouchTestActivity.txt](https://github.com/couchbase/couchbase-lite-java-ce-root/files/5902584/MultipleCouchTestActivity.txt)
[crash_log.txt](https://github.com/couchbase/couchbase-lite-java-ce-root/files/5902585/crash_log.txt)

**Comment by bmeike** [comment]
I believe that this was fixed in version 2.8.4.  Please update the ticket if you are still seeing the issue.
