### ISSUE TITLE
IllegalStateException("Tmp dir root is null") com.couchbase.lite.internal.CouchbaseLiteInternal.makeTmpPath

### ISSUE THREAD

**Issue by sinan-kalkan** [couchbase/couchbase-lite-java-ce-root#15]
Hello,

currently we recognize more crashes while initializing Couchbase on some device types like Huawei, Sony, Motorla within generating the external file dir from Android 7 to 10 OS. Is there any workaround planned for this situations to be handled in the near future? Here the full stacktrace:

Caused by java.lang.IllegalStateException: Tmp dir root is null at com.couchbase.lite.internal.CouchbaseLiteInternal.makeTmpPath(CouchbaseLiteInternal.java:153) at com.couchbase.lite.internal.CouchbaseLiteInternal.initDirectories(CouchbaseLiteInternal.java:216) at com.couchbase.lite.internal.CouchbaseLiteInternal.init(CouchbaseLiteInternal.java:95) at com.couchbase.lite.CouchbaseLite.init(CouchbaseLite.java:53) at com.couchbase.lite.CouchbaseLite.init(CouchbaseLite.java:35) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202) at android.app.ActivityThread.access$2200(ActivityThread.java:296) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:213) at android.app.ActivityThread.main(ActivityThread.java:8178) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Is there probably a connection to newly introduced scoped storages for Android 11 https://developer.android.com/about/versions/11/privacy/storage ? 

Android configs:

targetSdkVersion 30
Couchbase lite android version: 2.8.1

**Comment by bmeike** [comment]
Yes.  This is a known issue.  The target version for Couchbase Lite is 27.

Created JIRA ticket https://issues.couchbase.com/browse/CBL-1885 to track the issue

**Comment by benjaminglatzeder** [comment]
Is this issue in anyway related to the [issue](https://github.com/couchbase/couchbase-lite-android-ce/issues/31) I posted in late 2019? I never followed-up on it and might as well do it now. In the last 30 days the issue appeared on Android 6 through Android 11 and on dozens of different manufacturers. So it never went away.

@sinan-kalkan did you see any similar issues before publishing your update with `targetSdkVersion 30`?

I'm currently on CBL 2.7.1 and `targetSdkVersion 29`. My next update will target sdk 30 and ship with CBL 2.8.5. If the two issues are related I don't think I'll see more crashes than usual and I'm happy to go ahead with it!

**Comment by bmeike** [comment]
https://issues.couchbase.com/browse/CBL-1885 has been closed.
