### ISSUE TITLE
Miss flag attachment in saveConflictResolver

### ISSUE THREAD

**Issue by giallon** [couchbase/couchbase-lite-java-ce-root#17]
Hi,
The method saveResolvedDocument in AbstractDatabase don't add attachment flag in current reversion. 
Them, last attachment taking in previous local revision isn't pushed to remote server.

However, I already fix it in local repository. I will create PR soon.

https://forums.couchbase.com/t/conflict-resolver-dont-sync-blob/31053

**Comment by bmeike** [comment]
Not accepting this PR, directly, because the fix needs to go on the master branch, where the code looks slightly different.
I've filed https://issues.couchbase.com/browse/CBL-2180 to track the fix for the next release.  Many thanks, @giallon!
