### ISSUE TITLE
Make the replication Lifecycle-aware in the Couchbase Lite Android SDK

### ISSUE THREAD

**Issue by Thomas-Boutin** [couchbase/couchbase-lite-java-ce-root#18]
Hello,

I'm not sure if it's the right place to write this feature request. If so I apologize.

Currently, the Couchbase Lite Android SDK forces us to manually stop the replication when the App goes in the background.
As the functions stop and start are asynchronous, we can't really ensure that the replication is really stopped.

Today, most of the Android SDKs can subscribe to [lifecycle owner events](https://developer.android.com/topic/libraries/architecture/lifecycle).
For the couchbase lite SDK, we could imagine that : 
- any ongoing replication would automatically stop when the observed lifecycle owner is in a PAUSED or STOPPED state
- any ongoing replication would automatically start / restart when the observed lifecycle owner is in a RESUMED or STARTED state

This behaviour would drastically increase the apps' resilience.
For instance, a websocket that belongs to an app in the background can be closed by the Android System. 
This leads to really sneaky bugs and issues.

I'd be glad to help if you have any questions or require further explanation.

Cheers,
Thomas

**Comment by bmeike** [comment]
@Thomas-Boutin :
This is exactly the right place to request the feature!

I will forward this request to our PM, to see if we can't get it into our backlog.

**Comment by Thomas-Boutin** [comment]
Great thanks :-) 
Feel free to contact me

**Comment by bmeike** [comment]
@Thomas-Boutin 
the next release of CouchbaseLite will contain a WorkManager powered Replicator.

**Comment by Thomas-Boutin** [comment]
Hi ! Great news! 
Is there already somewhere a glance of documentation to see how it'd work?
