### ISSUE TITLE
ReplicatorType enum not visible in Kotlin

### ISSUE THREAD

**Issue by damianogiusti** [couchbase/couchbase-lite-java-ce-root#6]
**Artifact**: com.couchbase.lite:couchbase-lite-android:**2.6.0**
**Kotlin version**: 1.3.60

Steps to reproduce:
1. Create a `Database` and a `ReplicatorConfiguration`;
2. Set the replicator type using:
```
val config: ReplicatorConfiguration = ...
config.replicatorType = ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL
```
as documented under Java [here](https://docs.couchbase.com/couchbase-lite/2.6/java.html#starter-code)

The `ReplicatorType` enum is not visible because is declared inside a package-private class, named `AbstractReplicatorConfiguration`.

This prevents Kotlin users (such as most of the Android community) to customize the replicator type. Android Studio complains the following error:
```
Type AbstractReplicatorConfiguration.ReplicatorType is inaccessible in this context due to: public final enum class ReplicatorType : Enum<AbstractReplicatorConfiguration.ReplicatorType> defined in com.couchbase.lite.AbstractReplicatorConfiguration
```

**Fix proposal**
Move the `ReplicatorType` enum to a separate file. The class is public so I guess that the nesting inside the `AbstractReplicatorConfiguration` class has been chosen only for _namespacing_ purposes.

**Comment by bmeike** [comment]
Fixed in CouchbaseLite Android/Java 2.8.4
